---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: learn-rust
  namespace: flux-system
spec:
  path: ./k8s/app
  prune: true
  commonMetadata:
    labels:
      app.kubernetes.io/custom-part-of: learn
  sourceRef:
    kind: GitRepository
    name: learn-rust
    namespace: flux-system
  wait: true
  interval: 1m
  retryInterval: 1m
  timeout: 5m
