apiVersion: builtin
kind: LabelTransformer
metadata:
  name: labels
labels:
  app.kubernetes.io/cluster: learn
  app.kubernetes.io/custom-part-of: learn
  app.kubernetes.io/managed-by: fluxcd
  app.kubernetes.io/instance: learn-rust
  app.kubernetes.io/usage: learn
fieldSpecs:
  - path: metadata/labels
    create: true
