{{- if .Values.httproute.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "base.fullname" . }}
  labels:
    {{- include "base.labels" . | nindent 4 }}
  {{- with .Values.httproute.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.httproute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.httproute.parentRefs }}
  parentRefs:
    {{- toYaml . | nindent 4 }}
  {{- else }}
  parentRefs:
  - name: {{ .Values.httproute.gatewayName | default "gateway" }}
    {{- with .Values.httproute.gatewayNamespace }}
    namespace: {{ . }}
    {{- end }}
    {{- with .Values.httproute.sectionName }}
    sectionName: {{ . }}
    {{- end }}
  {{- end }}
  {{- with .Values.httproute.hostnames }}
  hostnames:
    {{- range . }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.httproute.rules }}
    - {{- with .matches }}
      matches:
        {{- range . }}
        - {{- with .path }}
          path:
            type: {{ .type | default "PathPrefix" }}
            value: {{ .value | default "/" }}
          {{- end }}
          {{- with .headers }}
          headers:
            {{- range . }}
            - type: {{ .type | default "Exact" }}
              name: {{ .name }}
              value: {{ .value }}
            {{- end }}
          {{- end }}
          {{- with .queryParams }}
          queryParams:
            {{- range . }}
            - type: {{ .type | default "Exact" }}
              name: {{ .name }}
              value: {{ .value }}
            {{- end }}
          {{- end }}
          {{- with .method }}
          method: {{ . }}
          {{- end }}
        {{- end }}
      {{- end }}
      {{- with .filters }}
      filters:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      backendRefs:
        {{- range .backendRefs }}
        - name: {{ .name | default (include "base.fullname" $) }}
          {{- with .namespace }}
          namespace: {{ . }}
          {{- end }}
          port: {{ .port | default $.Values.service.port }}
          {{- with .weight }}
          weight: {{ . }}
          {{- end }}
          {{- with .filters }}
          filters:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
    {{- end }}
{{- end }}
