kind: Secret
apiVersion: v1
metadata:
  name: {{ include "base.fullname" . }}-secret
  labels:
{{ include "base.labels" $ | indent 4 }}
stringData:
  SAMPLE_ENV: prod
  {{- range $key, $value := .Values.env.variables }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
type: Opaque
