apiVersion: v2
name: "learn-rust"
description: "Helm chart for learn-rust API"
type: application
version: "0.1.0" # {"$imagepolicy": "playground:learn-rust-policy:tag"}
appVersion: "0.1.0" # {"$imagepolicy": "playground:learn-rust-policy:tag"}
maintainers:
  - name: "Daniel Ramirez <dxas90@gmail.com>"
